server:
  port: 8081

spring:
  application:
    name: gamebacklog
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/gamebacklog
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql
